import type { OrgGraph, TeamId } from "../model/org-graph";
import { parseRepoSlug } from "./codeowners";

export interface AgentsMdFile {
  /** `owner/repo`, parsed from the service's `repository` URL. */
  repo: string;
  /** Path under `--out`, mirroring where the file belongs: `<owner>/<repo>/AGENTS.md`. */
  path: string;
  content: string;
  teamId: TeamId;
  services: string[];
}

export interface AgentsMdPackage {
  files: AgentsMdFile[];
  conflicts: Array<{ repo: string; teamIds: TeamId[] }>;
  skipped: Array<{ teamId: TeamId; service: string; reason: string }>;
}

function section(heading: string, body: string): string {
  return body.trim() ? `\n## ${heading}\n\n${body.trim()}\n` : "";
}

function list(items: string[]): string {
  return items.map((i) => `- ${i}`).join("\n");
}

/** A first line that survives being read out of context, which is how agents read. */
function title(services: string[], teamName: string): string {
  const what = services.length === 1 ? services[0]! : services.join(", ");
  return `# ${what} — owned by ${teamName}`;
}

/**
 * Renders what an agent opening this repository would otherwise have to guess: whose code it is,
 * what the words mean here, what the team has already decided, and who to ask.
 *
 * Everything comes from the team that declares a service in this repository. Nothing is
 * summarised or rewritten — steering documents and policies are the team's own words, so an agent
 * reading them is reading what a reviewer would quote back.
 */
export function renderAgentsMd(graph: OrgGraph, teamId: TeamId, services: string[]): string {
  const doc = graph.teams.get(teamId)!.doc;
  const owned = doc.services.filter((s) => services.includes(s.name));

  const parts: string[] = [`${title(services, doc.info.name)}\n`];
  if (doc.info.focus?.trim()) parts.push(`\n${doc.info.focus.trim()}\n`);

  const channel = doc.channels.find((c) => c.type === "slack");
  parts.push(
    section(
      "Who owns this",
      [
        `**${doc.info.name}** (\`${teamId}\`), a ${doc.info.type} team.`,
        channel ? `Ask in #${channel.name.replace(/^#/, "")}.` : "",
      ]
        .filter(Boolean)
        .join(" "),
    ),
  );

  // the ubiquitous language is the highest-value block here: it's the difference between an agent
  // naming a thing the way the team names it and inventing a synonym
  const terms = owned.flatMap((s) => s.boundedContext?.ubiquitousLanguage ?? []);
  parts.push(section("Ubiquitous language", list(terms.map((t) => `**${t.term}** — ${t.definition}`))));

  const published = [...new Set(owned.flatMap((s) => s.boundedContext?.publishedEvents ?? []))].sort();
  const subscribed = [...new Set(owned.flatMap((s) => s.boundedContext?.subscribedEvents ?? []))].sort();
  parts.push(
    section(
      "Domain events",
      [
        published.length ? `Publishes: ${published.join(", ")}` : "",
        subscribed.length ? `Subscribes to: ${subscribed.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n\n"),
    ),
  );

  const policies = doc.policies ?? [];
  parts.push(
    section(
      "Policies",
      list(
        policies.map((p) => {
          const detail = p.description?.trim().replace(/\s+/g, " ");
          return `**${p.name}** (${p.severity})${detail ? ` — ${detail}` : ""}`;
        }),
      ),
    ),
  );

  const steering = doc.steeringDocuments ?? [];
  parts.push(section("How this team works", steering.map((s) => `### ${s.title}\n\n${s.body.trim()}`).join("\n\n")));

  const specs = doc.specifications ?? [];
  parts.push(section("Specifications", list(specs.map((s) => `**${s.title}** (${s.kind}, ${s.status})`))));

  parts.push(
    section(
      "Where this came from",
      `Generated by TeamAPI from \`${teamId}\`'s teamapi.yml. Change it there, in a pull request — ` +
        `edits to this file are overwritten.`,
    ),
  );

  return (
    parts
      .filter(Boolean)
      .join("")
      .replace(/\n{3,}/g, "\n\n")
      .trimStart() + "\n"
  );
}

/**
 * One `AGENTS.md` per repository the org owns.
 *
 * This is the widest-reach AI integration in the toolchain precisely because it needs no runtime:
 * no gateway, no server, no adoption decision. Any coding agent that opens the repository reads
 * the file, because that is already the convention.
 *
 * Repos claimed by two teams are reported rather than merged, the same call
 * `buildCodeowners` makes — two teams' policies in one file would read as one team's.
 */
export function buildAgentsMd(graph: OrgGraph): AgentsMdPackage {
  const byRepo = new Map<string, Map<TeamId, string[]>>();
  const skipped: AgentsMdPackage["skipped"] = [];

  for (const teamId of [...graph.teams.keys()].sort()) {
    for (const service of graph.teams.get(teamId)!.doc.services) {
      if (!service.repository) {
        skipped.push({ teamId, service: service.name, reason: "no repository declared" });
        continue;
      }
      const repo = parseRepoSlug(service.repository);
      if (!repo) {
        skipped.push({ teamId, service: service.name, reason: `unrecognised repository URL '${service.repository}'` });
        continue;
      }
      const teams = byRepo.get(repo) ?? new Map<TeamId, string[]>();
      teams.set(teamId, [...(teams.get(teamId) ?? []), service.name]);
      byRepo.set(repo, teams);
    }
  }

  const files: AgentsMdFile[] = [];
  const conflicts: AgentsMdPackage["conflicts"] = [];

  for (const [repo, teams] of [...byRepo.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const teamIds = [...teams.keys()].sort();
    if (teamIds.length > 1) {
      conflicts.push({ repo, teamIds });
      continue;
    }
    const teamId = teamIds[0]!;
    const services = teams.get(teamId)!.slice().sort();
    files.push({
      repo,
      path: `${repo}/AGENTS.md`,
      teamId,
      services,
      content: renderAgentsMd(graph, teamId, services),
    });
  }

  return { files, conflicts, skipped };
}
