import type { OrgGraph, TeamId } from "../model/org-graph";

/** A CODEOWNERS file destined for one repository. */
export interface CodeownersFile {
  /** `owner/repo`, parsed from the service's `repository` URL. */
  repo: string;
  /** Path under `--out`, mirroring where the file belongs: `<owner>/<repo>/CODEOWNERS`. */
  path: string;
  content: string;
  teamId: TeamId;
  /** The service names in this repository, which is why the team owns it. */
  services: string[];
}

/** Two teams declaring services in the same repository. Not a syntax error — a real question
 * about who is accountable, which is precisely the thing this project exists to surface. */
export interface CodeownersConflict {
  repo: string;
  teamIds: TeamId[];
}

export interface CodeownersSkip {
  teamId: TeamId;
  service: string;
  reason: string;
}

export interface CodeownersPackage {
  files: CodeownersFile[];
  conflicts: CodeownersConflict[];
  skipped: CodeownersSkip[];
}

export interface CodeownersOptions {
  /**
   * GitHub org. Given one, ownership is written as `@org/team-id` — the same team slug
   * `teamapi apply` provisions, so the two commands agree. Without it, the members'
   * `githubUsername`s are listed instead, which drifts as people move but needs no org setup.
   */
  org?: string;
}

/** `https://github.com/acme/checkout-api.git` → `acme/checkout-api`. Returns null for anything
 * that isn't a two-segment path, since CODEOWNERS has nowhere to go without `owner/repo`. */
export function parseRepoSlug(repository: string): string | null {
  const trimmed = repository.trim().replace(/\.git$/, "").replace(/\/+$/, "");
  const withoutScheme = trimmed.replace(/^[a-z+]+:\/\//i, "").replace(/^git@([^:]+):/i, "$1/");
  const segments = withoutScheme.split("/").filter(Boolean);
  if (segments.length < 3) return null; // host + owner + repo
  return segments.slice(-2).join("/");
}

function ownersFor(graph: OrgGraph, teamId: TeamId, org?: string): string[] {
  if (org) return [`@${org}/${teamId}`];
  const team = graph.teams.get(teamId);
  const handles = (team?.doc.members ?? [])
    .map((m) => m.githubUsername)
    .filter((u): u is string => Boolean(u))
    .map((u) => `@${u.replace(/^@/, "")}`);
  return [...new Set(handles)].sort();
}

function render(team: { id: TeamId; name: string; focus?: string }, services: string[], owners: string[]): string {
  return [
    "# Generated by TeamAPI — edit the team's teamapi.yml, not this file.",
    `# Owner: ${team.name} (${team.id})`,
    `# Because it owns: ${services.join(", ")}`,
    "",
    `* ${owners.join(" ")}`,
    "",
  ].join("\n");
}

/**
 * Turns declared service ownership into CODEOWNERS files, one per repository.
 *
 * The index is inverted on the way: Team API is written per team, while CODEOWNERS lives per
 * repository, so a repo claimed by two teams has no single correct answer. Rather than pick one
 * or merge them, those repos are reported as conflicts and no file is emitted for them.
 *
 * Only the root `*` rule is written. Team API models which team owns a service, not which
 * directories inside a repository belong to whom, so any path-level rule would be invented.
 */
export function buildCodeowners(graph: OrgGraph, options: CodeownersOptions = {}): CodeownersPackage {
  const byRepo = new Map<string, { teamIds: Set<TeamId>; services: Map<TeamId, string[]> }>();
  const skipped: CodeownersSkip[] = [];

  for (const teamId of [...graph.teams.keys()].sort()) {
    const team = graph.teams.get(teamId)!;
    for (const service of team.doc.services) {
      if (!service.repository) {
        skipped.push({ teamId, service: service.name, reason: "no repository declared" });
        continue;
      }
      const repo = parseRepoSlug(service.repository);
      if (!repo) {
        skipped.push({ teamId, service: service.name, reason: `unrecognised repository URL '${service.repository}'` });
        continue;
      }
      const entry = byRepo.get(repo) ?? { teamIds: new Set<TeamId>(), services: new Map<TeamId, string[]>() };
      entry.teamIds.add(teamId);
      entry.services.set(teamId, [...(entry.services.get(teamId) ?? []), service.name]);
      byRepo.set(repo, entry);
    }
  }

  const files: CodeownersFile[] = [];
  const conflicts: CodeownersConflict[] = [];

  for (const [repo, entry] of [...byRepo.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const teamIds = [...entry.teamIds].sort();
    if (teamIds.length > 1) {
      conflicts.push({ repo, teamIds });
      continue;
    }
    const teamId = teamIds[0]!;
    const owners = ownersFor(graph, teamId, options.org);
    const services = entry.services.get(teamId)!.slice().sort();
    if (owners.length === 0) {
      for (const service of services) {
        skipped.push({ teamId, service, reason: "no --org and no member has a githubUsername" });
      }
      continue;
    }
    const doc = graph.teams.get(teamId)!.doc;
    files.push({
      repo,
      path: `${repo}/CODEOWNERS`,
      teamId,
      services,
      content: render({ id: teamId, name: doc.info.name, focus: doc.info.focus }, services, owners),
    });
  }

  return { files, conflicts, skipped };
}
