import * as YAML from "js-yaml";
import type { OrgGraph, TeamId } from "../model/org-graph";

export interface OtelServiceAttributes {
  service: string;
  teamId: TeamId;
  attributes: Record<string, string>;
}

export interface OtelFile {
  path: string;
  content: string;
}

export interface OtelPackage {
  services: OtelServiceAttributes[];
  files: OtelFile[];
}

/**
 * `OTEL_RESOURCE_ATTRIBUTES` is W3C Baggage: comma-separated `key=value`, so any comma, equals
 * sign or space in a value has to be percent-encoded or it silently truncates the list. Team
 * focus lines are full of commas, which makes this the difference between working and quietly
 * dropping every attribute after the first.
 */
export function encodeBaggageValue(value: string): string {
  return encodeURIComponent(value);
}

export function resourceAttributesLine(attributes: Record<string, string>): string {
  return Object.entries(attributes)
    .map(([key, value]) => `${key}=${encodeBaggageValue(value)}`)
    .join(",");
}

/**
 * Ownership as telemetry resource attributes, so a trace, a metric and an alert all know which
 * team to attribute themselves to without anyone tagging by hand.
 *
 * `service.name` and `service.namespace` are the semantic-convention attributes. Everything else
 * lives under a `teamapi.` prefix: OpenTelemetry has no standard attribute for "which team owns
 * this", and putting an org-specific concept in the reserved namespace is how you end up
 * colliding with a future spec revision.
 */
export function buildOtelAttributes(graph: OrgGraph): OtelServiceAttributes[] {
  const out: OtelServiceAttributes[] = [];

  for (const teamId of [...graph.teams.keys()].sort()) {
    const doc = graph.teams.get(teamId)!.doc;
    const channel = doc.channels.find((c) => c.type === "slack");

    for (const service of doc.services) {
      const attributes: Record<string, string> = {
        "service.name": service.name,
        "service.namespace": teamId,
        "teamapi.team": teamId,
        "teamapi.team_name": doc.info.name,
        "teamapi.topology": doc.info.type,
      };
      if (channel) attributes["teamapi.channel"] = channel.name.replace(/^#/, "");
      if (service.repository) attributes["teamapi.repository"] = service.repository;
      out.push({ service: service.name, teamId, attributes });
    }
  }

  return out.sort((a, b) => a.service.localeCompare(b.service));
}

/**
 * A collector `transform` processor that stamps the same attributes centrally, keyed on
 * `service.name`.
 *
 * This is the half that works without redeploying anything: the env files below need every
 * service's deployment touched, whereas this needs one collector config. Both are emitted because
 * which one you can actually land depends on who owns the collector.
 */
export function buildCollectorConfig(services: OtelServiceAttributes[]): string {
  // one OTTL statement per attribute: the grammar is a single editor followed by an optional
  // `where`, so chaining `set(...) set(...)` on one line does not parse
  const statements = services.flatMap((entry) =>
    Object.entries(entry.attributes)
      .filter(([key]) => key !== "service.name")
      .map(
        ([key, value]) =>
          `set(attributes["${key}"], ${JSON.stringify(value)}) ` +
          `where attributes["service.name"] == ${JSON.stringify(entry.service)}`,
      ),
  );

  return YAML.dump(
    {
      processors: {
        "transform/teamapi": {
          error_mode: "ignore",
          trace_statements: [{ context: "resource", statements }],
          metric_statements: [{ context: "resource", statements }],
          log_statements: [{ context: "resource", statements }],
        },
      },
    },
    { lineWidth: -1, noRefs: true },
  );
}

/** Env files per service plus one collector config, since which one you can land depends on
 * whether you own the deployments or the collector. */
export function buildOtelPackage(graph: OrgGraph): OtelPackage {
  const services = buildOtelAttributes(graph);
  const files: OtelFile[] = services.map((entry) => ({
    path: `${entry.service}.env`,
    content:
      `# ${entry.service} — owned by ${entry.teamId}\n` +
      `# Generated by TeamAPI. Values are percent-encoded: OTEL_RESOURCE_ATTRIBUTES is W3C Baggage.\n` +
      `OTEL_RESOURCE_ATTRIBUTES=${resourceAttributesLine(entry.attributes)}\n`,
  }));

  files.push({ path: "collector.yaml", content: buildCollectorConfig(services) });
  return { services, files };
}
