import * as path from "node:path";
import { describe, expect, it } from "vitest";
import { buildOrgGraph } from "../resolve/graph-builder";
import { buildAgentsMd, renderAgentsMd } from "../generators/agents-md";

const ACME_ROOT = path.resolve(__dirname, "../../../../examples/acme-org");
const CHECKOUT_SEED = path.join(ACME_ROOT, "stream-checkout/teamapi.yml");
const acme = () => buildOrgGraph({ seedUris: [CHECKOUT_SEED] });

const fileFor = (files: { repo: string; content: string }[], repo: string) =>
  files.find((f) => f.repo === `acme-example/${repo}`)!;

describe("buildAgentsMd — examples/acme-org", () => {
  it("writes one file per repository, where the repository expects it", async () => {
    const { files } = buildAgentsMd(await acme());
    expect(files.map((f) => f.path)).toEqual([
      "acme-example/checkout-api/AGENTS.md",
      "acme-example/ledger/AGENTS.md",
      "acme-example/onboarding-api/AGENTS.md",
      "acme-example/payments-api/AGENTS.md",
    ]);
  });

  it("opens with a line that stands on its own out of context", async () => {
    const { files } = buildAgentsMd(await acme());
    expect(fileFor(files, "checkout-api").content.split("\n")[0]).toBe("# checkout-api — owned by Stream Checkout");
  });

  it("names the owning team, its topology type and where to ask", async () => {
    const { files } = buildAgentsMd(await acme());
    const md = fileFor(files, "checkout-api").content;
    expect(md).toContain("**Stream Checkout** (`stream-checkout`), a stream-aligned team.");
    expect(md).toContain("Ask in #stream-checkout.");
  });

  it("carries the ubiquitous language, which is the point of the exercise", async () => {
    const { files } = buildAgentsMd(await acme());
    const md = fileFor(files, "checkout-api").content;
    expect(md).toContain("## Ubiquitous language");
    expect(md).toContain("**Cart** — An in-progress, unpaid order");
    expect(md).toContain("**Order** — A cart that has been placed and paid for");
  });

  it("lists published and subscribed events separately", async () => {
    const { files } = buildAgentsMd(await acme());
    const md = fileFor(files, "checkout-api").content;
    expect(md).toContain("Publishes: OrderPlaced");
    expect(md).toContain("Subscribes to: ApplicantActivated, ChargeAuthorized");
  });

  it("reproduces a blocking policy in the team's own words", async () => {
    const { files } = buildAgentsMd(await acme());
    const md = fileFor(files, "onboarding-api").content;
    expect(md).toContain("**No autonomous AI agents on applicant PII** (blocking)");
    expect(md).toContain("regulated PII");
  });

  it("says where the file came from, so nobody edits it in place", async () => {
    const { files } = buildAgentsMd(await acme());
    expect(fileFor(files, "checkout-api").content).toContain(
      "Generated by TeamAPI from `stream-checkout`'s teamapi.yml",
    );
  });

  it("omits sections a team has nothing for, rather than leaving empty headings", async () => {
    const graph = await acme();
    const checkout = graph.teams.get("stream-checkout")!.doc;
    checkout.policies = [];
    checkout.steeringDocuments = [];
    checkout.specifications = [];

    const md = renderAgentsMd(graph, "stream-checkout", ["checkout-api"]);
    expect(md).not.toContain("## Policies");
    expect(md).not.toContain("## How this team works");
    expect(md).not.toContain("## Specifications");
    expect(md).toContain("## Who owns this");
  });

  it("never leaves a run of blank lines behind an omitted section", async () => {
    const graph = await acme();
    graph.teams.get("stream-checkout")!.doc.policies = [];
    expect(renderAgentsMd(graph, "stream-checkout", ["checkout-api"])).not.toMatch(/\n{3}/);
  });

  it("refuses to merge two teams into one file", async () => {
    const graph = await acme();
    graph.teams.get("platform-payments")!.doc.services.push({
      name: "checkout-shim",
      repository: "https://github.com/acme-example/checkout-api",
    });

    const { files, conflicts } = buildAgentsMd(graph);
    expect(conflicts).toEqual([
      { repo: "acme-example/checkout-api", teamIds: ["platform-payments", "stream-checkout"] },
    ]);
    expect(files.some((f) => f.repo === "acme-example/checkout-api")).toBe(false);
  });

  it("covers every service when one repository holds several", async () => {
    const graph = await acme();
    graph.teams.get("stream-checkout")!.doc.services.push({
      name: "checkout-worker",
      repository: "https://github.com/acme-example/checkout-api",
    });

    const { files } = buildAgentsMd(graph);
    expect(fileFor(files, "checkout-api").content.split("\n")[0]).toBe(
      "# checkout-api, checkout-worker — owned by Stream Checkout",
    );
  });

  it("skips a service with no repository to put a file in", async () => {
    const graph = await acme();
    graph.teams.get("stream-checkout")!.doc.services.push({ name: "checkout-ui" });

    const { skipped } = buildAgentsMd(graph);
    expect(skipped).toContainEqual({
      teamId: "stream-checkout",
      service: "checkout-ui",
      reason: "no repository declared",
    });
  });
});
